
# a dictionary with problem name as key and array of filenames as value.
# first filename is the reference solution, while the rest are student solutions
problems = {
    'air': [
        'air.py',
        'air_1.py',
        'air_2.py',
        'air_3.py',
        'air_4.py',
        'air_5.py',
        'air_6.py',
        'air_7.py',
        'air_8.py',
        'air_9.py',
        'air_10.py',
    ],
    'arithmetic_seq': [
        'arithmetic_seq.py',
        'arithmetic_seq_1.py',
        'arithmetic_seq_2.py',
        'arithmetic_seq_3.py',
        'arithmetic_seq_4.py',
    ],
    'digits': [
        'digits.py',
        'digits_1.py',
    ],
    'is_allowed_to_buy': [
        'is_allowed_to_buy.py',
        'is_allowed_to_buy_1.py',
        'is_allowed_to_buy_2.py',
        'is_allowed_to_buy_3.py',
        'is_allowed_to_buy_4.py',
        'is_allowed_to_buy_5.py',
        'is_allowed_to_buy_6.py',
        'is_allowed_to_buy_7.py',
        'is_allowed_to_buy_8.py',
        'is_allowed_to_buy_9.py',
        'is_allowed_to_buy_10.py',
    ],
    'is_ordered': [
        'is_ordered.py',
        'is_ordered_1.py',
    ],
    'max_3': [
        'max_3.py',
        'max_3_1.py',
        'max_3_2.py',
        'max_3_3.py',
        'max_3_4.py',
        'max_3_5.py',
        'max_3_6.py',
        'max_3_7.py',
        'max_3_8.py',
        'max_3_9.py',
        'max_3_10.py',
        'max_3_11.py',
        'max_3_v1.py',
        'max_3_v2.py',
        'max_3_v3.py',
        'max_3_v4.py',
        'max_3_v5.py',
    ],
    'mid_3': [
        'mid_3.py',
        'mid_3_1.py',
    ],
    'min_3': [
        'min_3.py',
        'min_3_1.py',
        'min_3_2.py',
        'min_3_3.py',
        'min_3_4.py',
        'min_3_5.py',
    ],
    'no_of_triangle': [
        'no_of_triangle.py',
        'no_of_triangle_1.py',
        'no_of_triangle_2.py',
        'no_of_triangle_3.py',
        'no_of_triangle_4.py',
        'no_of_triangle_5.py',
        'no_of_triangle_6.py',
        'no_of_triangle_7.py',
        'no_of_triangle_8.py',
        'no_of_triangle_9.py',
        'no_of_triangle_10.py',
    ],
    'pow3abs': [
        'pow3abs.py',
        'pow3abs_1.py',
    ],
    'segiempat': [
        'segiempat.py',
        'segiempat_1.py',
        'segiempat_2.py',
        'segiempat_3.py',
        'segiempat_4.py',
        'segiempat_5.py',
        'segiempat_6.py',
        'segiempat_7.py',
        'segiempat_8.py',
        'segiempat_9.py',
        'segiempat_10.py',
        'segiempat_11.py',
    ],
    'student_grade': [
        'student_grade.py',
        'student_grade_1.py',
        'student_grade_2.py',
        'student_grade_3.py',
        'student_grade_4.py',
        'student_grade_5.py',
        'student_grade_6.py',
        'student_grade_7.py',
        'student_grade_8.py',
        'student_grade_9.py',
        'student_grade_10.py',
    ],
    'sum_20': [
        'sum_20.py',
        'sum_20_1.py',
        'sum_20_2.py',
        'sum_20_3.py',
        'sum_20_str.py',
    ],
}